Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "webserver1" do |machine|
    machine.vm.network "private_network", ip: "172.17.177.21"
  end
  config.vm.define "webserver2" do |machine|
    machine.vm.network "private_network", ip: "172.17.177.22"
  end
  config.vm.define "database" do |machine|
    machine.vm.network "private_network", ip: "172.17.177.23"
  end
  config.vm.define 'controller' do |machine|
    machine.vm.network "private_network", ip: "172.17.177.11"
    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.verbose = true
      ansible.config_file = "ansible.cfg"
      ansible.install = true
      ansible.limit = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "inventory"
    end
  end
end