- hosts: controller
  tasks:
    - name: ensure vim is at the latest version
      apt: name=vim state=latest
- hosts: nodes
  tasks:
   - name: copy a test file
     copy: src=cmd-test.txt dest=/home/vagrant
   - name: delete a test file
     file: path=/home/vagrant/cmd-test.txt state=absent
   - name: ensure vim is at the latest version
     apt: name=vim state=latest
   - name: ensure htop is at the latest version
     apt: name=htop state=latest
     become: true
     notify:
       - test handler
  handlers:
     - name: test handler
       debug: msg="Handler de test"
- hosts: webserver
  tasks:
    - name: install Apache
      apt: name=apache2 state=latest
      become: true