- hosts: controller
  tasks:
    - name: ensure vim is at the latest version
      apt: name=vim state=latest
- hosts: nodes
  roles:
    - common
  tasks:
   - name: copy a test file
     copy: src=cmd-test.txt dest=/home/vagrant
   - name: delete a test file
     file: path=/home/vagrant/cmd-test.txt state=absent
   - name: ensure template file is copy
     template: src=template.txt dest=~/template.txt
     when: var_test is defined
- hosts: webserver
  roles:
    - common
  tasks:
  - import_tasks: common_tasks.yml