- hosts: webserver
  tasks:
    - name: ensure apache httpd is present
      apt: name=apache2 state=present
      become: true
    - name: ensure httpd service is started
      service: name=apache2 state=started
      become: true